### PR TITLE
Implement Implement Plane Strike game based on TFLite using interpreter

### PR DESCRIPTION
**Pull request by st-tuanmai**

### CODE REVIEW

**Comment by PaulTR** [comment]
Please change the directory root to reinforcement_learning/ios

**Comment by PaulTR** [comment]
Functionality looks good, let's just make sure we replace every instance of 'battleship' with 'reinforcement_learning'. Thanks!

**Comment by PaulTR** [comment]
All of the paths that are 'battleship' need to be updated

**Comment by PaulTR** [comment]
Following up on this since it's pretty much ready to merge and just waiting on all instances of the word 'battleship' being replaced with reinforcement_learning.

**Comment by PaulTR** [comment]
If this only works with 1 model for now, get rid of the model selection option.

**Comment by st-tuanmai** [comment]
> Following up on this since it's pretty much ready to merge and just waiting on all instances of the word 'battleship' being replaced with reinforcement_learning.

sorry, I missed it.

**Comment by st-tuanmai** [comment]
> Following up on this since it's pretty much ready to merge and just waiting on all instances of the word 'battleship' being replaced with reinforcement_learning.

Hi Paul, I created new pull request:
https://github.com/google-ai-edge/interpreter-samples/pull/10

**Pull request closed without merging**
